apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: akka-projection-testing
  namespace: akka
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: appka
  podMetricsEndpoints:
    - port: metrics
      interval: 10s
