include "r2dbc"
include "local-shared"

akka.http.server.enable-http2 = on

akka.projection.grpc.consumer {
  client {
    host = "127.0.0.1"
    host = ${?SERVICE_GRPC_HOST}
    port = ${test.http.port}
    port = ${?SERVICE_GRPC_PORT}
    use-tls = false
  }
  stream-id = "events"
}

akka.projection.grpc.producer.query-plugin-id = "akka.persistence.r2dbc.query"