apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: projection-testing
spec:
  replicas: 12
  image: 803424716218.dkr.ecr.us-east-1.amazonaws.com/akka-projection-testing:latest
  javaOptions: "-Xlog:gc -Dakka.persistence.journal.plugin=akka.persistence.cassandra.journal -Dakka.persistence.snapshot-store.plugin=akka.persistence.cassandra.snapshot -Dakka.persistence.cassandra.journal.keyspace=lightbend -Dakka.persistence.cassandra.snapshot.keyspace=lightbend"
#  javaOptions: "-Xlog:gc -Dakka.persistence.journal.plugin=jdbc-journal -Dakka.persistence.snapshot-store.plugin=jdbc-snapshot-store"
  imagePullPolicy: Always
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"
      cpu: "1500m"
  httpPort: "8080"
  grpcPort: "off"
  cassandraDataStaxAstra:
    credentialsSecret: projection-testing-astra-secret
  jdbc:
    credentialsSecret: projection-testing-jdbc-secret
  roles:
    - name: "read-model"
      replicasRatio: 50
      replicasMax: 4 # there are 4 tags
    - name: "write-model"
      replicasRatio: 50
