apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appka
  name: appka
spec:
  replicas: 5
  selector:
    matchLabels:
      app: appka
  template:
    metadata:
      labels:
        app: appka
        actorSystemName: appka
      annotations:
        config.linkerd.io/skip-inbound-ports: 2552,8558
        config.linkerd.io/skip-outbound-ports: 2552,8558
    spec:
      containers:
        - name: appka
          image: docker.io/patriknw/akka-projection-testing:latest
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "2Gi"
              cpu: "1200m"
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            # akka-management and bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75 -Dconfig.resource=r2dbc.conf -Dakka.persistence.r2dbc.connection-factory.initial-size=20 -Dakka.persistence.r2dbc.connection-factory.max-size=40"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"
