name: "Build Setup"
description: "Composite action steps for setting up builds"
runs:
  using: "composite"
  steps:
    - name: Checkout - GitHub merge
      if: github.event.pull_request
      shell: bash
      run: |-
        git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
        git checkout scratch

    - name: Cache - Coursier
      # https://github.com/coursier/cache-action/releases
      # v6.4.5
      uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

    - name: Coursier - set up JDK 21
      # https://github.com/coursier/setup-action/releases
      # v1.3.5
      uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
      with:
        jvm: temurin:1.21
