name: Validate and test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  check-code-style:
    name: Checks
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-projection-testing'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Build setup
        uses: ./.github/actions/build-setup

      - name: Code style check
        run: |-
          cp .jvmopts-ci .jvmopts
          sbt verifyCodeStyle

  test-r2dbc:
    name: Run tests - R2DBC
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-projection-testing'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Run integration test
        uses: ./.github/actions/integration-test
        with:
          docker-compose: r2dbc-postgres
          test-config: local-r2dbc

  test-dynamodb:
    name: Run tests - DynamoDB
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-projection-testing'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Run integration test
        uses: ./.github/actions/integration-test
        with:
          docker-compose: dynamodb
          test-config: local-dynamodb

  test-jdbc:
    name: Run tests - JDBC
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-projection-testing'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Run integration test
        uses: ./.github/actions/integration-test
        with:
          docker-compose: jdbc-postgres
          test-config: local-jdbc

  test-cassandra:
    name: Run tests - Cassandra
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/akka-projection-testing'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Run integration test
        uses: ./.github/actions/integration-test
        with:
          docker-compose: cassandra-jdbc-postgres
          test-config: local-cassandra
